### PR TITLE
Dynamic golang roles

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by BenFradet** [comment]
@jbeemster Should I update the roles used in the different golang repos?

**Comment by jbeemster** [comment]
Hey @BenFradet I would:

1. Leave the current `golang.yml` role named as it is so the other repos do not break.
2. Update it so it is pointing to `1.7.4` as this was the last default
3. Add a role called `golang-1.8.0.yml` pointing to your new version

**Comment by BenFradet** [comment]
@jbeemster done :+1:

**Comment by jbeemster** [comment]
Perfect! LGTM!

**Pull request merged**
