### PR TITLE
Bump go to 1.8

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Do we know this won't break any of our Golang projects?

**Comment by jbeemster** [comment]
Other Go Projects:

- https://github.com/snowplow/sql-runner
- https://github.com/snowplow/snowplow-golang-tracker
- https://github.com/snowplow/snowplow-tracking-cli

**Comment by alexanderdean** [comment]
Maybe we should just version the thing, append 1.8, that would be safest. Then projects can control their own dependencies...

**Comment by BenFradet** [comment]
It might break tests, I'm running 1.8 on my machine and a few error messages seem to have changed:

```
go test ./build/src -tags test -v -covermode=count -coverprofile=build/coverage/coverage.out
=== RUN   TestInitAvroResolver
--- PASS: TestInitAvroResolver (0.00s)
=== RUN   TestParseClusterRecord_Success
--- PASS: TestParseClusterRecord_Success (0.00s)
=== RUN   TestParseClusterRecord_Fail
--- FAIL: TestParseClusterRecord_Fail (0.00s)
        Error Trace:    config_resolver_test.go:273
	Error:      	Not equal: 
	            	expected: "json: cannot unmarshal object into Go value of type string"
	            	received: "json: cannot unmarshal object into Go struct field SelfDescribingRecord.Schema of type string"
=== RUN   TestParsePlaybookRecord_Success
--- PASS: TestParsePlaybookRecord_Success (0.00s)
=== RUN   TestParsePlaybookRecord_Fail
--- FAIL: TestParsePlaybookRecord_Fail (0.00s)
        Error Trace:    config_resolver_test.go:324
	Error:      	Not equal: 
	            	expected: "json: cannot unmarshal object into Go value of type string"
	            	received: "json: cannot unmarshal object into Go struct field SelfDescribingRecord.Schema of type string"
=== RUN   TestToSelfDescribingRecord
--- PASS: TestToSelfDescribingRecord (0.00s)
=== RUN   TestTemplateRawBytes
--- PASS: TestTemplateRawBytes (0.00s)
=== RUN   TestGetJobFlowInput_Success
--- FAIL: TestGetJobFlowInput_Success (0.00s)
        Error Trace:    emr_cluster_test.go:99
	Error:      	Not equal: 
	            	expected: "strconv.ParseInt: parsing \"h\": invalid syntax"
	            	received: "strconv.Atoi: parsing \"h\": invalid syntax"
=== RUN   TestGetJobFlowInput_Fail
--- PASS: TestGetJobFlowInput_Fail (0.00s)
=== RUN   TestTerminateJobFlows_Fail
--- PASS: TestTerminateJobFlows_Fail (0.00s)
=== RUN   TestRunJobFlow_Fail
--- PASS: TestRunJobFlow_Fail (0.00s)
=== RUN   TestGetJobFlowStepsInput_Success
--- PASS: TestGetJobFlowStepsInput_Success (0.00s)
=== RUN   TestGetJobFlowStepsInput_Fail
--- PASS: TestGetJobFlowStepsInput_Fail (0.00s)
=== RUN   TestAddJobFlowSteps_Fail
--- PASS: TestAddJobFlowSteps_Fail (0.00s)
=== RUN   TestSetLogLevel
--- PASS: TestSetLogLevel (0.00s)
=== RUN   TestGetCredentialsProvider
--- PASS: TestGetCredentialsProvider (0.00s)
=== RUN   TestInterfaceToJSONString
--- PASS: TestInterfaceToJSONString (0.00s)
FAIL

```

**Comment by BenFradet** [comment]
cf https://beta.golang.org/doc/go1.8#encoding_json

**Comment by BenFradet** [comment]
>Maybe we should just version the thing, append 1.8, that would be safest. Then projects can control their own dependencies...

@alexanderdean I'm not sure to get what you mean?

**Comment by jbeemster** [comment]
Like these ones @BenFradet (https://github.com/snowplow/ansible-playbooks/blob/master/scala-2.10.5.yml)

**Comment by BenFradet** [comment]
Ok, I'll update the PR.

**Comment by BenFradet** [comment]
Closing in favor of #116

**Pull request closed without merging**
